# Update all the sections by editing the data.yml file inside _data folder.

# Site Settings

# SEO plugin
title: Resume
author: Mike Koser
tagline: Full Stack Developer
description: Mike Koser's digital resume

url: "https://heykos.github.io"
baseurl: "/resume" # change it according to your repository name

twitter:
  username:
  card: summary

social:
  links:
    - https://github.com/heykos

google_site_verification: # Put your google verification tag here

# End SEO

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: berry # gray blue turquoise green berry red

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
